include classpath("application.conf")

queues {
  # Creates a queue named "insight-jobs" on startup
  insight-jobs {
    defaultVisibilityTimeout = 10 seconds
    delay = 5 seconds
    receiveMessageWait = 0 seconds
  }
}